a = input('Digite algo: ')
print('O tipo primitivo desse valor é', type(a))
print('Só tem espaços? ', a.isspace())
print('É um número? ', a.isnumeric())
print('É alfabético? ', a.isalpha())
print('Ésta em maiúsculas? ', a.isupper())
print('Ésta em minúsculas?', a.islower())
print('Ésta capitalizada? ', a.istitle())
